#!/usr/bin/env bash
# Push domains.list and /etc/ai-proxy/servers.list into a running v2rayA.
# Re-running this is how you change anything; it does not reinstall.
set -euo pipefail

# Overridable so this can be exercised against a throwaway instance without root.
# The defaults are what a real install uses.
CONF_DIR="${AI_PROXY_CONF_DIR:-/etc/ai-proxy}"
API="${AI_PROXY_API:-http://127.0.0.1:2017/api}"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOMAINS="$HERE/domains.list"
SERVERS="$CONF_DIR/servers.list"
SOCKS_PORT=20170
HTTP_PORT=20171

usage() {
  cat <<EOF
usage: sudo ./apply.sh [option]

  (no option)        apply domains.list and servers.list; connect if nothing is connected
  --list             show known servers and which one is in use
  --server NAME|ID   connect to this server
  --update-subs      refresh every subscription first
  -h, --help         this text
EOF
}

SERVER_Q=''; DO_LIST=''; DO_SUBS=''
while [ $# -gt 0 ]; do
  case "$1" in
    --list) DO_LIST=1 ;;
    --server) shift; [ $# -gt 0 ] || { usage; exit 2; }; SERVER_Q=$1 ;;
    --update-subs) DO_SUBS=1 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "unknown option: $1" >&2; usage; exit 2 ;;
  esac
  shift
done

die() { echo "error: $*" >&2; exit 1; }

[ -n "${AI_PROXY_CONF_DIR:-}" ] || [ "$(id -u)" -eq 0 ] || die "run as root: sudo ./apply.sh"
[ -r "$CONF_DIR/admin.secret" ] || die "$CONF_DIR/admin.secret not found — run ./install.sh first"

TOKEN=''
login() {
  TOKEN=$(curl -sS -X POST "$API/login" -H 'Content-Type: application/json' \
    --data "$(jq -nc --arg u admin --rawfile p "$CONF_DIR/admin.secret" \
              '{username:$u, password:($p|rtrimstr("\n"))}')" \
    | jq -r '.data.token // empty')
  [ -n "$TOKEN" ] || die "login failed — is v2raya running, and does $CONF_DIR/admin.secret still match?"
}

api() { # api METHOD PATH [JSON-BODY]
  if [ $# -ge 3 ]; then
    curl -sS -X "$1" "$API/$2" -H "Authorization: $TOKEN" -H 'Content-Type: application/json' --data "$3"
  else
    curl -sS -X "$1" "$API/$2" -H "Authorization: $TOKEN"
  fi
}

check() { # check RESPONSE CONTEXT
  [ "$(jq -r '.code' <<<"$1")" = 'SUCCESS' ] \
    || die "$2: $(jq -r '.message // "unknown error"' <<<"$1")"
}

# Every server, from both plain entries and subscriptions, as a flat list.
inventory() {
  api GET touch | jq -c '
    .data.touch as $t
    | (($t.servers // []) | map({_type:"server", id, sub:0, name, address}))
      + ((($t.subscriptions // []) | to_entries
          | map(.key as $s | (.value.servers // []) | map({_type:"subscriptionServer", id, sub:$s, name, address})))
         | add // [])
    | . as $all
    | ($t.connectedServer // []) as $c
    | $all | map(. + {connected: (. as $s | any($c[]; ._type == $s._type and .id == $s.id and (.sub // 0) == $s.sub))})
  '
}

login

if [ -n "$DO_LIST" ]; then
  inventory | jq -r '
    if length == 0 then "no servers yet — add them to '"$SERVERS"' and run: sudo ./apply.sh"
    else (.[] | "\(if .connected then "*" else " " end) \(.id)  \(.name)  \(.address)")
    end'
  exit 0
fi

if [ -n "$DO_SUBS" ]; then
  echo "==> refresh subscriptions"
  for id in $(api GET touch | jq -r '(.data.touch.subscriptions // [])[].id'); do
    echo "    subscription $id"
    check "$(api PUT subscription "$(jq -nc --argjson i "$id" '{_type:"subscription", id:$i}')")" "subscription $id"
  done
fi

echo "==> inbound ports"
# socks5/http are deliberately disabled: those two inbounds ignore the routing
# rules and shove everything into the tunnel. The *WithPac inbounds are the ones
# that honour them, so the rule ports get the familiar numbers instead.
check "$(api PUT ports "$(jq -nc --argjson s "$SOCKS_PORT" --argjson h "$HTTP_PORT" \
  '{socks5:0, http:0, socks5WithPac:$s, httpWithPac:$h, vmess:0, api:{port:0, services:null}}')")" "ports"

echo "==> routing mode and DNS"
# pacMode=routingA switches to our own rules (the default, whitelist, sends every
# non-Chinese domain through the tunnel). dnsListenAddr defaults to 0.0.0.0:52353,
# which really does open a resolver on every interface once the core starts.
check "$(api PUT setting "$(api GET setting | jq -c '.data.setting
  | .pacMode = "routingA"
  | .dnsListenAddr = "127.0.0.1:52353"')")" "setting"

echo "==> domain rules"
[ -r "$DOMAINS" ] || die "$DOMAINS not found"
matchers=$(awk '!/^[[:space:]]*(#|$)/ { gsub(/[[:space:]]/, ""); print }' "$DOMAINS" | paste -sd, -)
[ -n "$matchers" ] || die "$DOMAINS lists no domains"
rules=$(printf '# generated by apply.sh from domains.list — edit that file, not this box\ndefault: direct\ndomain(%s)->proxy\n' "$matchers")
check "$(api PUT routingA "$(jq -nc --arg r "$rules" '{routingA:$r}')")" "domain rules"
echo "    $(awk '!/^[[:space:]]*(#|$)/' "$DOMAINS" | wc -l) domains routed through the proxy, everything else direct"

# A stable identity per line, so re-runs do not import the same server twice:
# host:port for share links, the URL itself for subscriptions.
link_key() {
  local l=$1 rest pad
  case "$l" in
    vmess://*)
      pad=${l#vmess://}
      while [ $(( ${#pad} % 4 )) -ne 0 ]; do pad="$pad="; done
      if rest=$(printf '%s' "$pad" | base64 -d 2>/dev/null | jq -er '"\(.add):\(.port)"' 2>/dev/null); then
        printf '%s' "$rest"; return
      fi
      ;;
    *://*)
      rest=${l#*://}; rest=${rest%%\#*}; rest=${rest%%\?*}; rest=${rest##*@}; rest=${rest%%/*}
      case "$rest" in *:*) printf '%s' "$rest"; return ;; esac
      ;;
  esac
  printf '%s' "$l"
}

if [ -s "$SERVERS" ]; then
  echo "==> servers"
  known=$(api GET touch)
  while IFS= read -r line || [ -n "$line" ]; do
    line=$(printf '%s' "$line" | tr -d '[:space:]')
    case "$line" in ''|'#'*) continue ;; esac
    key=$(link_key "$line")
    if jq -e --arg k "$key" '
          [ (.data.touch.servers // [])[].address,
            (.data.touch.subscriptions // [])[].address ] | index($k)' >/dev/null <<<"$known"; then
      echo "    known:     $key"
      continue
    fi
    echo "    importing: $key"
    check "$(api POST import "$(jq -nc --arg u "$line" '{url:$u}')")" "import $key"
    login  # importing servers can rotate the JWT secret
    known=$(api GET touch)
  done < "$SERVERS"
fi

echo "==> connection"
if [ -n "$SERVER_Q" ]; then
  which=$(inventory | jq -c --arg q "$SERVER_Q" '
    map(select(.name == $q or (.id | tostring) == $q))
    | if length == 0 then empty else .[0] | {_type, id, sub, outbound:"proxy"} end')
  [ -n "$which" ] || die "no server named or numbered '$SERVER_Q' — see: sudo ./apply.sh --list"
  # v2rayA can hold several connections at once, so POST alone would add one
  # rather than switch. Drop what is connected first.
  while read -r old; do
    [ -n "$old" ] || continue
    check "$(api DELETE connection "$old")" "disconnect"
  done < <(inventory | jq -c '.[] | select(.connected) | {_type, id, sub, outbound:"proxy"}')
  check "$(api POST connection "$which")" "connect"
elif [ "$(inventory | jq -r 'map(select(.connected)) | length')" = '0' ]; then
  which=$(inventory | jq -c 'if length == 0 then empty else .[0] | {_type, id, sub, outbound:"proxy"} end')
  if [ -z "$which" ]; then
    echo "    no servers yet — put them in $SERVERS and re-run: sudo ./apply.sh"
    exit 0
  fi
  check "$(api POST connection "$which")" "connect"
fi
inventory | jq -r '.[] | select(.connected) | "    connected: \(.name)  \(.address)"'

echo
echo "==> check"
probe() { curl -sS -o /dev/null -w '%{http_code}' --max-time 10 --proxy "$1" "$2" 2>/dev/null || true; }
printf '    example.com     via HTTP  %s   (expect 200 — direct, not through the tunnel)\n' \
  "$(probe "http://127.0.0.1:$HTTP_PORT" https://example.com/)"
printf '    api.openai.com  via HTTP  %s   (expect 401 — reached OpenAI through the tunnel)\n' \
  "$(probe "http://127.0.0.1:$HTTP_PORT" https://api.openai.com/v1/models)"
printf '    api.openai.com  via SOCKS %s   (expect 401)\n' \
  "$(probe "socks5h://127.0.0.1:$SOCKS_PORT" https://api.openai.com/v1/models)"

cat <<EOF

Point a single program at the proxy, leaving the rest of the machine alone:

  HTTPS_PROXY=http://127.0.0.1:$HTTP_PORT \\
  HTTP_PROXY=http://127.0.0.1:$HTTP_PORT \\
  ALL_PROXY=socks5h://127.0.0.1:$SOCKS_PORT \\
  <your-cli>
EOF
